# Generated by Django 3.1.4 on 2021-02-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inter_participant',
            fields=[
                ('paticipants_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=100)),
                ('groups', models.CharField(default='participant', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intra_participant',
            fields=[
                ('paticipants_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=100)),
                ('groups', models.CharField(default='participant', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='p_roll_no',
            new_name='p_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='conf_code',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='transferred',
        ),
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
