# Generated by Django 3.1.4 on 2021-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210219_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='username',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
