# Generated by Django 3.1.4 on 2021-03-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_intra_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('council_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('groups', models.CharField(default='council', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('council_id', models.IntegerField()),
                ('img', models.CharField(default='static/webapp/assets/images/profile.svg', max_length=100)),
                ('total_reg', models.IntegerField()),
                ('team', models.IntegerField(default=0)),
                ('class_cap', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inter_participant',
            fields=[
                ('paticipants_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('groups', models.CharField(default='participant', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=100)),
                ('event_id', models.IntegerField()),
                ('council_id', models.IntegerField()),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_no', models.IntegerField(default=1)),
                ('p1_id', models.IntegerField()),
                ('p2_id', models.IntegerField(blank=True, null=True)),
                ('p3_id', models.IntegerField(blank=True, null=True)),
                ('p1_name', models.CharField(max_length=100)),
                ('p2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('p3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
