# Generated by Django 3.1.4 on 2021-02-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_council_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='council_id',
            field=models.CharField(max_length=100),
        ),
    ]
