# Generated by Django 3.1.4 on 2021-02-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210220_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='council_name',
        ),
        migrations.AddField(
            model_name='event',
            name='council_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
