# Generated by Django 3.1.4 on 2021-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210225_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
