# Generated by Django 3.1.4 on 2021-02-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210225_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_reg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
