# Generated by Django 3.1.4 on 2021-02-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_id', models.IntegerField()),
                ('p2_id', models.IntegerField(blank=True, null=True)),
                ('p3_id', models.IntegerField(blank=True, null=True)),
                ('p1_name', models.CharField(max_length=100)),
                ('p2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('p3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='class_cap',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='p_class',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inter_participant',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inter_participant',
            name='phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='intra_participant',
            name='class_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='intra_participant',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='intra_participant',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
