# Generated by Django 3.1.4 on 2021-02-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210228_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamregistration',
            name='id',
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='phone',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='team_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
