# Generated by Django 3.1.4 on 2021-02-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20210228_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='p_class',
        ),
    ]
