# Generated by Django 3.1.4 on 2021-02-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_remove_registration_p_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamregistration',
            name='team_id',
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
